[workspace]
#members = ["lib", "phantoma", "sketches/maze"]
members = ["lib", "phantoma", "sketches/async"]
#members = ["lib", "phantoma", "sketches/*"]
exclude = ["sketches/new", "sketches/template"]

[profile.release]
debug = true
