[workspace]
#members = ["lib", "phantoma", "sketches/maze"]
members = ["lib", "wgpu_glyph", "wgpu_staging", "phantoma", "sketches/syn005"]
#members = ["lib", "phantoma", "sketches/*"]
exclude = ["sketches/new", "sketches/template"]

[profile.release]
debug = true
