[package]
name = "wgpu_staging"
version = "0.1.0"
authors = ["Jack Foltz <jack@foltz.io>"]
edition = "2018"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = "0.11"
futures = "0.3.7"
async-channel = "1.5.1"
