[package]
name = "maze"
version = "0.1.0"
authors = ["Jack Foltz <jack@foltz.io>"]
edition = "2018"

[dependencies]
nannou = "0.14.0"
lib = { path = "../../lib" }
log = "0.4.8"
num = "0.2.1"
tokio = { version = "0.2.21", features = ["full", "macros"] }
itertools = "0.9.0"
