[package]
name = "interp"
version = "0.1.0"
authors = ["Jack Foltz <jack@foltz.io>"]
edition = "2018"

[dependencies]
nannou = "0.14.0"
lib = { path = "../../lib" }
splines = { version = "3.3.0", features = ["impl-cgmath"] }
